services:
  user-service:
    build:
      context: ../../backend/user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/user_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=sapassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      mariadb:
        condition: service_healthy

  product-service:
    build:
      context: ../../backend/product-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/product_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=sapassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started

  order-service:
    build:
      context: ../../backend/order-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/order_db
    depends_on:
      - mongodb

  payment-service:
    build:
      context: ../../backend/payment-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/payment_db
      - PORT=8084
    depends_on:
      - mongodb

  frontend:
    build:
      context: ../../frontend/watch-store-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sapassword
      - MYSQL_DATABASE=user_db
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # Xóa hoặc comment dòng command dưới đây
    # command: --authentication-policy=mysql_native_password
    healthcheck:
      test: ["CMD", "mariadb", "-u", "root", "-psapassword", "-e", "SELECT 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mariadb_data:
  mongodb_data:
  redis_data: